apiVersion: v1
kind: Service
metadata:
  name: sujit-portfolio-service
spec:
  type: NodePort
  selector:
    app: sujit-portfolio
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
